"use client";

import { useRef } from "react";

/**
 * Landing page.
 *
 * The hero background is a real ForgeVid render (public/videos/hero.mp4) — the
 * product demonstrating itself. Same for every tile in the Examples strip: each
 * was generated by this platform from a one-line prompt, not sourced elsewhere.
 *
 * The video is decorative: it is muted, aria-hidden, carries a poster frame so
 * the first paint is never blank, and is hidden entirely under
 * prefers-reduced-motion (the poster shows instead).
 */

interface Example {
  slug: string;
  label: string;
  prompt: string;
  aspect: "16:9" | "9:16" | "1:1";
}

const EXAMPLES: Example[] = [
  {
    slug: "product",
    label: "Product ad",
    prompt: "Sleek marketing spot for wireless earbuds",
    aspect: "16:9",
  },
  {
    slug: "social",
    label: "Social reel",
    prompt: "A chef plating a colorful bowl of fresh food",
    aspect: "9:16",
  },
  {
    slug: "travel",
    label: "Travel reel",
    prompt: "Sunrise beaches, mountain ridges, lantern-lit streets",
    aspect: "1:1",
  },
  {
    slug: "realestate",
    label: "Property tour",
    prompt: "A modern home: living room, kitchen, garden at golden hour",
    aspect: "16:9",
  },
];

const STEPS = [
  {
    n: "01",
    title: "Describe it, or paste a URL",
    body: "Type what you want, or drop in a product page — ForgeVid reads it and writes a script grounded in what the page actually says.",
  },
  {
    n: "02",
    title: "It finds the footage and the voice",
    body: "Scenes are matched to real stock footage or your own uploads, narrated by an AI voice or your own recording, and cut to the speech.",
  },
  {
    n: "03",
    title: "Edit any scene, re-render in seconds",
    body: "Swap a clip, choose a specific image, retime a beat, or just say “make scene 2 faster”. Re-renders reuse cached narration.",
  },
];

/**
 * Every tile gets the SAME media height so the grid rows line up; the clip is
 * letter/pillar-boxed inside it (object-contain on black) rather than cropped.
 * Cropping a 9:16 reel into a 16:9 box — or the reverse — would hide exactly
 * the thing this section exists to show: that ForgeVid renders all three shapes.
 */
const MEDIA_BOX = "relative h-64 w-full overflow-hidden bg-black";

function ExampleTile({ example }: { example: Example }) {
  const videoRef = useRef<HTMLVideoElement>(null);

  // Play only while the user is looking at it: four autoplaying videos would
  // cost several megabytes and a lot of battery for no benefit.
  const play = () => {
    const video = videoRef.current;
    if (!video) return;
    video.play().catch(() => {
      /* autoplay policy — the poster stays up, which is fine */
    });
  };
  const stop = () => {
    const video = videoRef.current;
    if (!video) return;
    video.pause();
    video.currentTime = 0;
  };

  return (
    <figure
      className="glass-card group flex h-full flex-col overflow-hidden rounded-2xl hover-lift"
      onMouseEnter={play}
      onMouseLeave={stop}
      onFocus={play}
      onBlur={stop}
      tabIndex={0}
    >
      <div className={MEDIA_BOX}>
        {/* WebM first: some browsers (and headless Chromium) ship no H.264. */}
        <video
          ref={videoRef}
          className="absolute inset-0 h-full w-full object-contain"
          poster={`/videos/examples/${example.slug}.jpg`}
          muted
          loop
          playsInline
          preload="none"
        >
          <source src={`/videos/examples/${example.slug}.webm`} type="video/webm" />
          <source src={`/videos/examples/${example.slug}.mp4`} type="video/mp4" />
        </video>
        <span className="absolute right-2 top-2 rounded-md bg-black/60 px-2 py-0.5 text-[11px] font-medium text-gray-200 backdrop-blur">
          {example.aspect}
        </span>
        <span className="pointer-events-none absolute inset-0 flex items-center justify-center transition-opacity group-hover:opacity-0">
          <span className="flex h-12 w-12 items-center justify-center rounded-full bg-white/15 backdrop-blur">
            <svg className="ml-0.5 h-5 w-5 text-white" fill="currentColor" viewBox="0 0 24 24">
              <path d="M8 5v14l11-7z" />
            </svg>
          </span>
        </span>
      </div>
      <figcaption className="flex flex-1 flex-col p-4">
        <p className="text-sm font-semibold text-white">{example.label}</p>
        <p className="mt-1 text-xs leading-relaxed text-gray-400">“{example.prompt}”</p>
      </figcaption>
    </figure>
  );
}

export default function RootPage() {
  return (
    <div className="min-h-screen bg-[#070a12]">
      {/* ---------------------------------------------------------------- nav */}
      <header className="fixed inset-x-0 top-0 z-50 border-b border-white/5 bg-[#070a12]/70 backdrop-blur">
        <nav className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4">
          <a href="/" className="text-lg font-bold tracking-tight">
            <span className="gradient-text">Forge</span>
            <span className="text-white">Vid</span>
          </a>
          <div className="hidden items-center gap-8 text-sm text-gray-300 md:flex">
            <a href="#examples" className="transition-colors hover:text-white">Examples</a>
            <a href="#how" className="transition-colors hover:text-white">How it works</a>
            <a href="/pricing" className="transition-colors hover:text-white">Pricing</a>
          </div>
          <div className="flex items-center gap-3">
            <a
              href="/pricing"
              className="text-sm text-gray-300 transition-colors hover:text-white md:hidden"
            >
              Pricing
            </a>
            <a href="/auth/signin" className="text-sm text-gray-300 transition-colors hover:text-white">
              Sign in
            </a>
            <a
              href="/dashboard/ai"
              className="rounded-lg bg-gradient-to-r from-cyan-500 to-blue-600 px-4 py-2 text-sm font-semibold text-white shadow-lg transition-all hover:shadow-cyan-500/40"
            >
              Get started
            </a>
          </div>
        </nav>
      </header>

      {/* --------------------------------------------------------------- hero */}
      <section className="relative flex min-h-screen items-center justify-center overflow-hidden px-4">
        {/* The product, demonstrating itself. Decorative -> aria-hidden.
            WebM first: not every browser ships the H.264 decoder. */}
        <video
          className="hero-video absolute inset-0 h-full w-full object-cover"
          poster="/videos/hero-poster.jpg"
          autoPlay
          muted
          loop
          playsInline
          preload="auto"
          aria-hidden="true"
        >
          <source src="/videos/hero.webm" type="video/webm" />
          <source src="/videos/hero.mp4" type="video/mp4" />
        </video>

        {/* Scrim. Light enough to let the footage read, dark enough that the
            headline survives the brightest frame of the loop. The top/bottom
            gradient stays strong: it anchors the nav bar and blends into the
            next section. */}
        <div className="absolute inset-0 bg-black/35" />
        <div className="absolute inset-0 bg-gradient-to-b from-[#070a12] via-transparent to-[#070a12]" />
        <div className="absolute inset-0 bg-gradient-to-r from-[#070a12]/55 via-transparent to-[#070a12]/40" />

        <div className="relative z-10 mx-auto max-w-4xl py-32 text-center">
          <div className="glass-card mb-8 inline-flex items-center rounded-full border border-cyan-500/30 px-4 py-2">
            <span className="relative mr-2 flex h-2 w-2">
              <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-cyan-400 opacity-75" />
              <span className="relative inline-flex h-2 w-2 rounded-full bg-cyan-500" />
            </span>
            <span className="text-sm font-medium text-cyan-300">
              This background was made by ForgeVid
            </span>
          </div>

          {/* No trailing em-dash: it orphans onto its own line when the first
              line wraps, which looks like a typo. */}
          <h1 className="text-5xl font-bold leading-[1.05] tracking-tight text-white md:text-6xl lg:text-7xl">
            Turn a prompt — or a URL
            <br />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 via-purple-400 to-pink-400">
              into a finished video
            </span>
          </h1>

          <p className="mx-auto mt-8 max-w-2xl text-lg leading-relaxed text-gray-300 md:text-xl">
            ForgeVid writes the script, finds the footage, narrates it in a voice you
            choose — yours or an AI’s — and cuts every scene to the words. Paste your
            product’s URL and it builds the commercial from the page itself.
          </p>

          <div className="mt-12 flex flex-col items-center justify-center gap-4 sm:flex-row">
            <a
              href="/dashboard/ai"
              className="group relative rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 px-8 py-4 text-lg font-semibold text-white shadow-xl transition-all hover-lift glow-cyan hover:shadow-cyan-500/50"
            >
              Create my first video — free
            </a>
            <a
              href="#how"
              className="glass-card rounded-xl border border-purple-500/30 px-8 py-4 text-lg font-semibold text-white transition-all hover-lift hover:border-purple-400/60"
            >
              See how it works
            </a>
          </div>

          <p className="mt-6 text-sm text-gray-500">
            No credit card required · Made for TikTok, Reels &amp; Shorts (9:16) · Export in minutes
          </p>
        </div>

        <a
          href="#examples"
          className="absolute bottom-8 left-1/2 z-10 -translate-x-1/2 text-gray-500 transition-colors hover:text-gray-300"
          aria-label="Jump to examples"
        >
          <svg className="h-6 w-6 animate-bounce" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 14l-7 7m0 0l-7-7m7 7V3" />
          </svg>
        </a>
      </section>

      {/* ----------------------------------------------------------- examples */}
      <section id="examples" className="relative border-t border-white/5 px-4 py-24">
        <div className="absolute inset-0 tech-grid opacity-20" />
        <div className="relative mx-auto max-w-6xl">
          <div className="mb-12 text-center">
            <h2 className="text-3xl font-bold text-white md:text-4xl">Made with ForgeVid</h2>
            <p className="mx-auto mt-4 max-w-2xl text-gray-400">
              Every clip below was generated by this platform from the one-line prompt
              shown beneath it. Hover to play.
            </p>
          </div>

          <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">
            {EXAMPLES.map((example) => (
              <ExampleTile key={example.slug} example={example} />
            ))}
          </div>
        </div>
      </section>

      {/* -------------------------------------------------------- short-form */}
      <section id="shortform" className="border-t border-white/5 px-4 py-24">
        <div className="mx-auto max-w-6xl">
          <div className="mb-12 text-center">
            <span className="inline-block rounded-full border border-pink-500/30 bg-pink-500/10 px-4 py-1 text-sm font-medium text-pink-300">
              For creators
            </span>
            <h2 className="mt-4 text-3xl font-bold text-white md:text-4xl">Built for TikTok, Reels &amp; Shorts</h2>
            <p className="mx-auto mt-4 max-w-2xl text-gray-400">
              Short-form is first-class in ForgeVid — vertical, captioned, and ready to post. Not just repurposed 16:9.
            </p>
          </div>

          <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">
            <div className="glass-card rounded-2xl border border-white/10 p-6">
              <div className="mb-3 text-3xl">📱</div>
              <h3 className="mb-2 font-semibold text-white">Vertical 9:16</h3>
              <p className="text-sm text-gray-400">TikTok, Reels &amp; Shorts format out of the box — up to 4K portrait.</p>
            </div>
            <div className="glass-card rounded-2xl border border-white/10 p-6">
              <div className="mb-3 text-3xl">💬</div>
              <h3 className="mb-2 font-semibold text-white">Karaoke captions</h3>
              <p className="text-sm text-gray-400">Word-by-word highlighted captions — the style short-form viewers expect.</p>
            </div>
            <div className="glass-card rounded-2xl border border-white/10 p-6">
              <div className="mb-3 text-3xl">🎬</div>
              <h3 className="mb-2 font-semibold text-white">Your clips + talking head</h3>
              <p className="text-sm text-gray-400">Upload your own footage and overlay a talking-head of yourself on the b-roll.</p>
            </div>
            <div className="glass-card rounded-2xl border border-white/10 p-6">
              <div className="mb-3 text-3xl">🎤</div>
              <h3 className="mb-2 font-semibold text-white">Your voice or an AI’s</h3>
              <p className="text-sm text-gray-400">Record your own narration, or let an AI voice read your script.</p>
            </div>
          </div>

          <div className="mt-10 text-center">
            <a
              href="/dashboard/ai"
              className="group relative inline-block rounded-xl bg-gradient-to-r from-pink-500 to-purple-600 px-8 py-4 text-lg font-semibold text-white shadow-xl transition-all hover-lift hover:shadow-pink-500/50"
            >
              Make a short — free
            </a>
          </div>
        </div>
      </section>

      {/* ---------------------------------------------------------- how it works */}
      <section id="how" className="border-t border-white/5 px-4 py-24">
        <div className="mx-auto max-w-5xl">
          <div className="mb-16 text-center">
            <h2 className="text-3xl font-bold text-white md:text-4xl">How it works</h2>
            <p className="mx-auto mt-4 max-w-2xl text-gray-400">
              Three steps from an idea to something you can publish.
            </p>
          </div>

          <div className="grid grid-cols-1 gap-8 md:grid-cols-3">
            {STEPS.map((step) => (
              <div key={step.n} className="glass-card rounded-2xl p-8 hover-lift">
                <div className="gradient-text mb-4 text-4xl font-bold">{step.n}</div>
                <h3 className="mb-3 text-lg font-semibold text-white">{step.title}</h3>
                <p className="text-sm leading-relaxed text-gray-400">{step.body}</p>
              </div>
            ))}
          </div>

          <div className="mt-20 text-center">
            <h3 className="text-2xl font-bold text-white">Ready to make yours?</h3>
            <a
              href="/dashboard/ai"
              className="mt-8 inline-block rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 px-8 py-4 text-lg font-semibold text-white shadow-xl transition-all hover-lift glow-cyan"
            >
              Create my first video — free
            </a>
          </div>
        </div>
      </section>

      {/* ------------------------------------------------------------- footer */}
      <footer className="border-t border-white/5 px-4 py-10">
        <div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-4 text-sm text-gray-500 sm:flex-row">
          <span>© {new Date().getFullYear()} ForgeVid. All rights reserved. ForgeVid is owned and operated by Kryst Investments LLC.</span>
          <div className="flex items-center gap-6">
            <a href="/privacy" className="transition-colors hover:text-gray-300">Privacy</a>
            <a href="/terms" className="transition-colors hover:text-gray-300">Terms</a>
            <a href="/refund" className="transition-colors hover:text-gray-300">Refunds</a>
            <button
              onClick={(e) => {
                e.preventDefault();
                const btn = document.querySelector(
                  "[data-cookie-preferences-trigger]",
                ) as HTMLButtonElement | null;
                btn?.click();
              }}
              className="underline transition-colors hover:text-gray-300"
              data-testid="manage-cookies-link"
            >
              Manage Cookies
            </button>
          </div>
        </div>
      </footer>
    </div>
  );
}
